apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gaffer.fullname" . }}-schema
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
data:
{{- range $fileName, $contents := .Values.graph.schema }}
  {{ $fileName }}: {{ $contents | quote }}
{{- end }}
