apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaffer.fullname" . }}-masters
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  selector:
    {{- include "gaffer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: master
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
