apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gaffer.fullname" . }}-masters
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: {{ template "gaffer.fullname" . }}-masters
  selector:
    matchLabels:
      {{- include "gaffer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        {{- include "gaffer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: master
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/accumulo/config.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-for-namenode-startup
        image: {{ .Values.alpine.repository}}:{{ .Values.alpine.tag }}
        imagePullPolicy: {{ .Values.alpine.imagePullPolicy }}
        command: [
          "/bin/sh",
          "-c",
          'if [ {{ .Values.hdfs.enabled }} != "false" ]; then; for i in $(seq 1 100); do nc -z -w3 {{ template gaffer.hdfsNamenodeHostname .}} && exit 0 || sleep 3; done; exit 1; fi;'
        ]
      containers:
      - name: accumulo-master
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        args:
        - master
        env:
        - name: ACCUMULO_CONF_DIR
          value: /etc/accumulo/
        - name: ACCUMULO_INSTANCE_NAME
          value: {{ .Values.accumulo.instanceId }}
        volumeMounts:
        - name: config
          mountPath: /etc/accumulo/
          readOnly: true
        resources:
          {{- toYaml .Values.accumulo.master.resources | nindent 10 }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "gaffer.fullname" . }}-accumulo-config
          optional: false
      {{- with .Values.accumulo.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
