apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gaffer.fullname" . }}-masters
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  podManagementPolicy: Parallel
  replicas: 1
  serviceName: {{ template "gaffer.fullname" . }}-masters
  selector:
    matchLabels:
      {{- include "gaffer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        {{- include "gaffer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: master
    spec:
      containers:
      - name: accumulo-master
        image: {{ .Values.accumulo.image.repository }}:{{ .Values.accumulo.image.tag }}
        imagePullPolicy: {{ .Values.accumulo.image.pullPolicy }}
        args:
        - master
        env:
        - name: ACCUMULO_CONF_DIR
          value: /etc/accumulo/
        resources:
          {{- toYaml .Values.accumulo.master.resources | nindent 10 }}
      {{- with .Values.accumulo.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.accumulo.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
