apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaffer.fullname" . }}-api
  labels:
    {{- include "gaffer.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "gaffer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
