version: "3.7"

services:

  gaffer-wildfly:
    image: gchq/gaffer-wildfly:${GAFFER_VERSION}
    build:
      context: .
      args:
        GAFFER_VERSION: ${GAFFER_VERSION}
        GAFFER_TOOLS_VERSION: ${GAFFER_TOOLS_VERSION}
    restart: always
    ports:
    - 8080:8080
