
alpine:
  repository: alpine
  tag: 3.10.2
  imagePullPolicy: IfNotPresent

busybox:
  repository: busybox
  tag: 1.31.0
  imagePullPolicy: IfNotPresent

namenode:
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ports:
    http: 9870
    https: 9871
    clientRpc: 8020
    serviceRpc: 8021
    lifelineRpc: 8022
  dataVolumes:
    count: 1
    size: 10Gi
    storageClassName: ""
    uid: 1000
    gid: 1000

datanode:
  nodeCount: 3
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ports:
    http: 9864
    https: 9865
    data: 9866
    ipc: 9867
  dataVolumes:
    count: 2
    size: 10Gi
    storageClassName: ""
    uid: 1000
    gid: 1000

shell:
  enabled: true
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

config:
  path: /etc/hadoop/conf
  coreSite: {}
  hdfsSite:
    dfs.replication: 3

secrets:
  path: /etc/hadoop/secrets
  files: {}

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  host: ""
  pathPrefix: /hdfs/
  # For Nginx:
  #pathPrefix: "/hdfs/(.*)"
