apiVersion: v1
kind: Service
metadata:
  name: gaffer
  labels:
    app: gaffer
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gaffer
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop0000
  labels:
    app: hadoop0000
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: hadoop0000
---
apiVersion: v1
kind: Service
metadata:
  name: zk1
  labels:
    app: zk1
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk1
---
apiVersion: v1
kind: Service
metadata:
  name: zk2
  labels:
    app: zk2
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk2
---
apiVersion: v1
kind: Service
metadata:
  name: zk3
  labels:
    app: zk3
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: rpc
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: internal1
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: internal2
  selector:
    app: zk3
---
apiVersion: v1
kind: Service
metadata:
  name: accumulo0000
  labels:
    app: accumulo0000
spec:
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: master
  - port: 50091
    targetPort: 50091
    protocol: TCP
    name: gc
  - port: 9995
    targetPort: 9995
    protocol: TCP
    name: monitor
  - port: 12234
    targetPort: 12234
    protocol: TCP
    name: tracer
  - port: 42424
    targetPort: 42424
    protocol: TCP
    name: proxy
  - port: 10002
    targetPort: 10002
    protocol: TCP
    name: slave
  - port: 10001
    targetPort: 10001
    protocol: TCP
    name: replication
  selector:
    app: accumulo0000
