api:
  user: root

test:
  runIntegrationTests: true

accumulo:
  hdfs:
    postInstallCommands:
    - hadoop fs -mkdir -p /accumulo
    - hadoop fs -chown accumulo /accumulo
    - hadoop fs -chmod 700 /accumulo
    - hadoop fs -mkdir /tmp
    - hadoop fs -chown root /tmp
    - hadoop fs -chmod 777 /tmp
    - hadoop fs -ls /
  enabled: true
  config:
    userManagement:
      rootPassword: "root"
      users:
        tracer:
          password: "tracer"
    postInstallCommands:
    - setauths -u root -s vis1,vis2,publicVisibility,privateVisibility,public,private