
nameOverride: ""
fullnameOverride: ""

graph:
  config:
    graphId: "simpleGraph"
    description: "A graph for demo purposes"
    hooks: []

  schema:
    elements.json: |-
      {
        "edges": {
          "BasicEdge": {
            "source": "vertex",
            "destination": "vertex",
            "directed": "true",
            "properties": {
              "count": "count"
            }
          }
        },
        "entities": {
          "BasicEntity": {
            "vertex": "vertex",
            "properties": {
              "count": "count"
            }
          }
        },
        "types": {
          "vertex": {
            "class": "java.lang.String"
          },
          "count": {
            "class": "java.lang.Integer",
            "aggregateFunction": {
              "class": "uk.gov.gchq.koryphe.impl.binaryoperator.Sum"
            }
          },
          "true": {
            "description": "A simple boolean that must always be true.",
            "class": "java.lang.Boolean",
            "validateFunctions": [
              { "class": "uk.gov.gchq.koryphe.impl.predicate.IsTrue" }
            ]
          }
        }
      }


  storeProperties:
    gaffer.cache.service.class: uk.gov.gchq.gaffer.cache.impl.HashMapCacheService
    gaffer.store.job.tracker.enabled: true

hdfs:
  namenodeUri: hdfs://hdfs-namenode-0.hdfs-namenodes:8020
  volumes: hdfs://hdfs-namenode-0.hdfs-namenodes:8020/accumulo

zookeeper:
  enabled: true
  externalHosts: ""

  replicaCount: 1
  persistence:
    enabled: false

accumulo:
  image:
    repository: cybermaggedon/accumulo-gaffer
    tag: 1.9.1
    pullPolicy: IfNotPresent
    pullSecrets: []

  master:
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  tabletServers:
    replicaCount: 3
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  monitor:
    replicaCount: 1
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      host: ""
      # For Traefik:
      #pathPrefix: /accumulo/
      # For Nginx:
      pathPrefix: "/accumulo/(.*)"

api:
  replicaCount: 1
  image:
    repository: gchq/gaffer-wildfly
    tag: 0.0.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    host: ""
    # For Traefik:
    #pathPrefix: /gaffer/
    # For Nginx:
    pathPrefix: "/gaffer/(.*)"

testImages:
  curl:
    repository: curlimages/curl
    tag: 7.67.0
