
nameOverride: ""
fullnameOverride: ""

graph:
  config:
    graphId: "simpleGraph"
    description: "A graph for demo purposes"
    hooks: []
  schema: {}
    # elements.json: "{}"
  storeProperties:
    gaffer.cache.service.class: uk.gov.gchq.gaffer.cache.impl.HashMapCacheService
    gaffer.store.job.tracker.enabled: true

hdfs:
  # Config used by this chart
  enabled: true
  namenodeUri: hdfs://hdfs-namenodes:8020
  volumes: hdfs://hdfs-namenodes:8020/accumulo
  # Config used by hdfs sub-chart
  namenode:
    ports:
      clientRpc: 8020
  postInstallCommands:
  - hadoop fs -mkdir -p /accumulo
  - hadoop fs -chown accumulo /accumulo
  - hadoop fs -chmod 700 /accumulo
  - hadoop fs -ls /

zookeeper:
  enabled: true
  externalHosts: ""

  replicaCount: 1
  persistence:
    enabled: false

accumulo:
  instanceId: accumulo

  image:
    repository: gchq/gaffer
    tag: 1.11.0
    pullPolicy: IfNotPresent
    pullSecrets: []

  master:
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  tabletServers:
    replicaCount: 3
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  monitor:
    replicaCount: 1
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
      host: ""
      # For Traefik:
      #pathPrefix: /accumulo/
      # For Nginx:
      pathPrefix: "/accumulo/(.*)"

api:
  replicaCount: 1
  image:
    repository: gchq/gaffer-wildfly
    tag: 0.0.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    host: ""
    # For Traefik:
    #pathPrefix: /gaffer/
    # For Nginx:
    pathPrefix: "/gaffer/(.*)"

testImages:
  curl:
    repository: curlimages/curl
    tag: 7.67.0
